version: '3'

services:

#########Server##########

 server:
  build: ./server
  expose:
   - ${APP_SERVER_PORT}
  environment:
    API_HOST: ${API_HOST}
    APP_SERVER_PORT: ${APP_SERVER_PORT}
  ports:
    - ${APP_SERVER_PORT}: ${APP_SERVER_PORT}
  volumes:
    - ./server/:/usr/src/app-server  
  command: npm start

###########Client###################
 client:
  build: ./client
  expose:
   - ${REACT_APP_PORT}
  environment:
    REACT_APP_PORT: ${REACT_APP_PORT}
  ports:
    - ${REACT_APP_PORT}: ${REACT_APP_PORT}
  volumes:
    - ./clinet/src:/usr/src/app-client/src
    - ./clinet/public:/usr/src/app-client/build   
  command: npm start        